# .github/workflows/deploy-backend.yml
name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'render.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}