# .github/workflows/full-deploy.yml
name: Deploy Full Stack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy-backend]') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}

  # deploy-frontend:
  #   runs-on: ubuntu-latest
  #   needs: deploy-backend
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
      
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
      
  #     - name: Generate Frontend with Backend URL
  #       run: |
  #         # Create docs directory
  #         mkdir -p docs
          
  #         # Read backend URL from secrets/env
  #         BACKEND_URL="${{ secrets.BACKEND_URL }}"
          
  #         # Create index.html with the actual backend URL
  #         sed "s|https://kmlverification.onrender.com|${BACKEND_URL}|g" frontend/index.html > docs/index.html
      
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./docs